### ISSUE TITLE
How to break out of 'each' or 'reach' after x items?

### ISSUE THREAD

**Issue by j20** [vadimg/js_bintrees#17]
Thanks for the package!

Let's say you have 1,000 items, but only need the first 100. Using 'each' or 'reach' is there a way to break out of the iteration after x items?

I've tried 'return false' and 'break', but still get all the items.

**Comment by bvd** [comment]
maybe you can create a fork where you add the following to the reach and each methods in the treebase file as to support the return false solution you yourself are proposing

if(cb(data) === false) break

you could suggest the fork to be merged into the main version via a pull request

**Comment by j20** [comment]
Thanks for this! I've tested and submitted a PR https://github.com/vadimg/js_bintrees/pull/18

**Comment by vadimg** [comment]
Thanks for the pull request!
