### ISSUE TITLE
Inserting objects with sortable keys?

### ISSUE THREAD

**Issue by shaunlebron** [vadimg/js_bintrees#29]
Are there general guidelines for using this library with JS objects rather than just numbers?

Or are we expected to only insert sortable keys, then keep a separate map from the sortable keys to their respective objects?

```js
var RBTree = require('bintrees').RBTree;

var tree = new RBTree(function(a, b) { return a - b; });

var foo = {key: 2, value: "foo"};
var bar = {key: -3, value: "bar"};

var objects = {};
for (let o of [foo,bar]) {
  objects[o.key] = o;
  tree.insert(o.key);
}

const key = tree.lowerBound(0).data();
objects[key] // <-- returns foo
```

**Comment by darwayne** [comment]
@shaunlebron you just have to update your comparator.

e.g
```
var RBTree = require('bintrees').RBTree;

var tree = new RBTree(function(a, b) { return a.key - b.key; });
```

then you can insert the complete object into the tree

```
tree.insert({key: 1, value: "yo"})
```

and to get that object you'd just have to pass in an object with a key

```
item = tree.find({key: 1}) // returns  {key: 1, value: "yo"}
```

**Comment by shaunlebron** [comment]
@darwayne thank you!
